export const CIRCLE_RADIUS = 20
export const PENTAGRAM_LINE_HEIGHT = 15
export const NUMBER_OF_PENTAGRAM_LINES = 5
export const IDEAL_SPACING = 10
export const LINE_DIFF = 16
export const START_PENTAGRAM_COUNT = 3
export const START_BAR_COUNT = 3
export const MAX_NOTE_SIZE = (CIRCLE_RADIUS + 20) * 4
export const ZOOM_LEVEL = 2
